# Generated by Django 2.2.6 on 2019-11-06 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0095_organization_logo_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='tiebreaker',
            field=models.FloatField(default=0.0, verbose_name='tie-breaking field'),
        ),
    ]
